name 'tracywebtech-pip'
version '1.0.0'
source 'https://github.com/TracyWebTech/puppet-pip'
author 'Tracy Web Technologies'
summary 'Install pip using get-pip.py script'
description 'Downloads get-pip.py and run it in order to install pip.'
project_page 'https://github.com/TracyWebTech/puppet-pip'
